# Generated by Django 6.0.6 on 2026-06-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
                ('days', models.IntegerField()),
                ('travel_type', models.CharField(choices=[('Solo', 'Solo'), ('Couple', 'Couple'), ('Family', 'Family'), ('Friends', 'Friends')], max_length=20)),
                ('itinerary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
